### ISSUE TITLE
[BUG] TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Marietto2008** [jetsonhacks/jetsonUtilities#12]
root@zi-desktop:~/Desktop/Desktop_zi/Work/I9/Tools# git clone https://github.com/jetsonhacks/jetsonUtilities

Cloning into 'jetsonUtilities'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 108 (delta 6), reused 18 (delta 4), pack-reused 84
Receiving objects: 100% (108/108), 29.08 KiB | 620.00 KiB/s, done.
Resolving deltas: 100% (40/40), done.

root@zi-desktop:~/Desktop/Desktop_zi/Work/I9/Tools# cd jetsonUtilities

root@zi-desktop:~/Desktop/Desktop_zi/Work/I9/Tools/jetsonUtilities# python jetsonInfo.py

Traceback (most recent call last):
  File "jetsonInfo.py", line 22, in <module>
    (key, _, value) = line.partition("=")
TypeError: a bytes-like object is required, not 'str'

root@zi-desktop:~/Desktop/Desktop_zi/Work/I9/Tools/jetsonUtilities# ./jetsonInfo.py

Traceback (most recent call last):
  File "jetsonInfo.py", line 22, in <module>
    (key, _, value) = line.partition("=")
TypeError: a bytes-like object is required, not 'str'

root@zi-desktop:~/Desktop/Desktop_zi/Work/I9/Tools/jetsonUtilities# python

Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by middleprince** [comment]
@Marietto2008 That's not bug! you should use python2

**Comment by Marietto2008** [comment]
I can't use python 2. it causes problems with python 3. the author should upgrade the script,making it compatible with 3.

**Comment by middleprince** [comment]
> I can't use python 2. it causes problems with python 3. the author should upgrade the script,making it compatible with 3.

maybe you should choose the better tools [jtop](https://github.com/rbonghi/jetson_stats), which is better.

**Comment by Marietto2008** [comment]
it sounds nice !

**Comment by jetsonhacks** [comment]
Fixed in v2.2
