### ISSUE TITLE
Jetson nano detected as TX1

### ISSUE THREAD

**Issue by drakorg** [jetsonhacks/jetsonUtilities#7]
Hi, this happens on a fresh install of "Developer Preview of JetPack 4.4", downloaded from https://developer.nvidia.com/jetson-nano-sd-card-image, which redirects you to download a file called nv-jetson-nano-sd-card-image-r32.4.2.zip of size 5.91 GB, exactly 6,347,594,220 bytes.

When running jetsonInfo.py it says something about a TX1 although I'm running it on a Nano.
Following is ouput:

```
drakorg@drakorg-jetpack44:~/workspace/nspi/scripts/jetson-nano/jetsonUtilities$ sudo ./jetsonInfo.py
 NVIDIA Jetson TX1
 L4T 32.4.2 [ JetPack UNKNOWN ]
 Ubuntu 18.04.4 LTS
 Kernel Version: 4.9.140-tegra
 CUDA 10.2.89
```

It also states that the Jetpack version is unknown, when I would expect it to detect it as 4.4.
Thank you.
Best regards,
Eduardo

**Comment by jetsonhacks** [comment]
Fixed in version 2.1
